const types = {
  GET_WEB3: 'GET_WEB3',
  GET_CONTRACTS: 'GET_CONTRACTS',
  SET_ACCOUNT: 'SET_ACCOUNT',
  SET_CHAIN_ID: 'SET_CHAIN_ID',
  SET_TRANSFERS: 'SET_TRANSFERS',
  SET_IS_FETCHING: 'SET_IS_FETCHING',
  SET_BALANCE: 'SET_BALANCE',
};

export default types;
